AppBundle\Entity\Boards:
    type: entity
    table: boards
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        count:
            type: integer
            nullable: false
            options:
                unsigned: false
    oneToMany:
        tasks:
            targetEntity: Tasks
            cascade: {  }
            fetch: LAZY
            mappedBy: boards
            inversedBy: null
            joinColumns:
                id:
                    referencedColumnName: board_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
    repositoryClass: AppBundle\Repository\BoardsRepository